# training config
train: True
epochs: 10
batch_size: 32
eval_batch_size: 64
max_passing_steps: 4
loss_name: 'CE_weighted' # CE_weighted Focal BCE_weighted BCE
add_FPR: True
loss_weight: 'None'
loss_weight_custom: True
FPR_alpha: 1

# testing config
test: False
ckpt: ""
visualize: False

# common config
device: 'cuda'
output: './gnn_ckpt'
wildtrack: True
