# ###### MODEL CONFIG #####
lr: 0.0002
output_dir: './output'
device: 'cuda:0'
seed: 20230715
distributed: False
num_workers: 8

# ###### DATASET CONFIG ######
# The file name where WildTrack Dataset convert to COCO type to save
train_split: Wildtrack_train_coco
val_split: Wildtrack_train_cross_val_frame_0_5_to_1_0_coco
dataset: 'mot_wildTrack'
mot_path_train: 'D:\datasets\MOT\Wildtrack_dataset\wildtrack_train_coco' # train dataset root
mot_path_val: 'D:\datasets\MOT\Wildtrack_dataset\wildtrack_val_coco' # valid dataset root
track_prev_frame_rnd_augs: 0.01 # crop augment
track_prev_frame_range: 5 #  Range of possible random previous frames

img_transform:
  max_size: 1333
  val_width: 800

overflow_boxes: True


