# ###### MODEL CONFIG #####
lr: 0.0002
output_dir: './output'
device: 'cuda:0'
seed: 20230715
distributed: False
num_workers: 8
hidden_dim: 256 # Size of the embeddings (dimension of the transformer)
position_embedding: sine  # Type of positional embedding to use on top of the image features. ('sine', 'learned')


# ###### DATASET CONFIG ######
# The file name where WildTrack Dataset convert to COCO type to save
train_split: wildtrack_train_coco
val_split: Wildtrack_train_cross_val_frame_0_5_to_1_0_coco
dataset: 'mot_wildTrack'
#mot_path_train: 'D:\datasets\MOT\Wildtrack_dataset\wildtrack_train_coco' # train dataset root (fancy)
wildtrack_path_train: 'D:\datasets\Wildtrack_dataset_full\Wildtrack_dataset'  # train dataset root (kongcheng)
mot_path_val: 'D:\datasets\MOT\Wildtrack_dataset\wildtrack_val_coco' # valid dataset root
track_prev_frame_rnd_augs: 0.01 # crop augment
track_prev_frame_range: 5 #  Range of possible random previous frames
# Tracking
tracking: False
# Segmentation
masks: False
# Range of possible random previous frames
track_prev_prev_frame: False


img_transform:
  max_size: 1333
  val_width: 800

overflow_boxes: True

# only for vanilla DETR
multi_frame_attention: false
multi_frame_encoding: true


