# ###### MODEL CONFIG #####
lr: 0.0002
output_dir: './output'
device: 'cuda'
seed: 20230715
distributed: False
num_workers: 8
multi_frame_attention: False
hidden_dim: 256
position_embedding: "sine"
backbone: resnet50  # Name of the convolutional backbone to use. ('resnet50', 'resnet101')
dilation: False # If true, we replace stride with dilation in the last convolutional block (DC5)
num_queries: 300  # Number of object queries

# ###### MATCHER CONFIG #####
set_cost_class: 1.0 # Class coefficient in the matching cost
set_cost_bbox: 5.0  # L1 box coefficient in the matching cost
set_cost_giou: 2.0  # giou box coefficient in the matching cost
# Relative classification weight of the no-object class
focal_loss: True
focal_alpha: 0.25
focal_gamma: 2

# ###### LOSS CONFIG ######
aux_loss: True


# ###### DATASET CONFIG ######
# The file name where WildTrack Dataset convert to COCO type to save
train_split: wildtrack_train_coco
val_split: Wildtrack_train_cross_val_frame_0_5_to_1_0_coco
dataset: 'wildTrack'

wildtrack_path_train: 'D:\datasets\Wildtrack_dataset_full\Wildtrack_dataset'  # train dataset root (kongcheng)
#wildtrack_path_train: 'D:\dataset\MOT\Wildtrack_dataset'  # train dataset root (fancy)
mot_path_val: 'D:\datasets\MOT\Wildtrack_dataset\wildtrack_val_coco' # valid dataset root
track_prev_frame_rnd_augs: 1.0 # crop augment
track_prev_frame_range: 5 #  Range of possible random previous frames

# ###### Tracking CONFIG ######
tracking: False
track_query_false_positive_prob: 0.1
track_query_false_negative_prob: 0.4

# Segmentation
masks: False
# Range of possible random previous frames
track_prev_prev_frame: False
lr_backbone: 0.00002  # backbone train lr
num_feature_levels: 4 # Number of feature levels the encoder processes from the backbone

img_transform:
  max_size: 1333
  val_width: 800

overflow_boxes: True
batch_size: 1

# ####### DEFORMABLE CONFIG ######
deformable: True



# ############# DETR-transformer CONFIG ###########
dropout: 0.1
nheads: 8
dim_feedforward: 1024
enc_layers: 6
dec_layers: 6
pre_norm: False
